apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 # This port allows other objects to access the port inside the container
      targetPort: 3000 # port inside the container