apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432

# k8s volume is created inside pod object
  # when containers crash, the data still exists.
  # but when pod crash, the data does not exist.
# Persistent Voloume is cresated outside pod object
  # when containers crash, the data still exists.
  # but when pod crash, the data still exists.